let ADD_CONTENT = 'ADD_CONTENT'
let POST_DATA_FAILURE = 'POST_DATA_FAILURE'
let POST_DATA_REQUEST = 'POST_DATA_REQUEST'
let POST_DATA_SUCCESS = 'POST_DATA_SUCCESS'

let TEST = 'TEST'

export { ADD_CONTENT, TEST, POST_DATA_FAILURE, POST_DATA_REQUEST, POST_DATA_SUCCESS }