let ADD_CONTENT = 'ADD_CONTENT'
let POST_DATA_FAILURE = 'POST_DATA_FAILURE'
let POST_DATA_REQUEST = 'POST_DATA_REQUEST'
let POST_DATA_SUCCESS = 'POST_DATA_SUCCESS'
let GET_DATA_FAILURE = 'GET_DATA_FAILURE'
let GET_DATA_REQUEST = 'GET_DATA_REQUEST'
let GET_DATA_SUCCESS = 'GET_DATA_SUCCESS'


export {
    ADD_CONTENT,
    POST_DATA_FAILURE, POST_DATA_REQUEST,
    POST_DATA_SUCCESS,
    GET_DATA_FAILURE,
    GET_DATA_REQUEST,
    GET_DATA_SUCCESS
}